version: '3.9'
services:
  postgres:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: B2k25ismine@1$
      POSTGRES_DB: nest_auth
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    restart: always
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata:
